steps:
  # Build the React app
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
    dir: '.'

  - name: 'node:18'
    entrypoint: 'bash'
    args: 
      - '-c'
      - 'echo "REACT_APP_API_URL=https://admin-panel-backend-693306869303.us-central1.run.app" > .env && cat .env && npm run build'
    dir: '.'

  # Build Docker image for the frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/admin-panel-frontend:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/admin-panel-frontend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'admin-panel-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/admin-panel-frontend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=https://admin-panel-backend-693306869303.us-central1.run.app'

images:
  - 'gcr.io/$PROJECT_ID/admin-panel-frontend:latest'
