steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tax-filing-backend:latest'
      - '--file'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tax-filing-backend:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tax-filing-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tax-filing-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,FIREBASE_PROJECT_ID=tax-filing-app-3649f,GCS_PROJECT_ID=tax-filing-app-472019,GCS_BUCKET_NAME=tax-filing-documents-tax-filing-app-472019'

images:
  - 'gcr.io/$PROJECT_ID/tax-filing-backend:latest'
